services:
  bot:
    image: danielwuhoo/dingle-unleashed:master
    container_name: dingle-bot
    env_file: .env.bot
    restart: unless-stopped
    volumes:
      - ./data:/opt/app/data

  activity:
    image: danielwuhoo/dingle-activity:master
    container_name: dingle-activity
    env_file: .env.activity
    restart: unless-stopped
    ports:
      - "6767:3000"
    volumes:
      - ./data:/opt/app/data
