name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.12
      - run: yarn
      - run: yarn build
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: danielwuhoo/dingle-unleashed
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BRISKET_LOVE_HOST }}
          username: ${{ secrets.BRISKET_LOVE_USER }}
          key: ${{ secrets.BRISKET_LOVE_SSH_KEY }}
          port: 6969
          script: |
            docker pull danielwuhoo/dingle-unleashed:master
            docker stop dingle-unleashed || true
            docker rm dingle-unleashed || true
            docker run -d --restart unless-stopped --name dingle-unleashed --env-file dingle-unleashed/.env danielwuhoo/dingle-unleashed:master